//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class CVDbContext : DbContext
    {
        public CVDbContext()
            : base("name=CVDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> COMPANIES { get; set; }
        public virtual DbSet<CompanyContent> COMPANYINFO { get; set; }
        public virtual DbSet<Error> ERRORS { get; set; }
        public virtual DbSet<ProjectContent> PROJECTINFO { get; set; }
        public virtual DbSet<Project> PROJECTS { get; set; }
    }
}
